### ISSUE TITLE
Before/After are not returned as longs on certain endpoints

### ISSUE THREAD

**Issue by devax** [bchavez/Coinbase.Pro#32] opened 2021-01-30 15:36 UTC
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |   3.3.0     |
| .NET Core?                   |    .NET 5  |
| .NET Full Framework?   |        -       |
| Windows OS?              |     Win 10  |
| Linux OS?                    |         -        |
| Visual Studio?              |      2019    |

### What is the expected behavior?
When calling ```Client.Orders.GetAllOrdersAsync```, the response object should have values set in "After" and "Before" properties.

### What is the actual behavior?
The response object has ```After``` and ```Before``` set to ```null```

### Any possible solutions?
Apparently, the endpoint from Coinbase does not return a long value for the orders endpoint. Instead, a DateTime value is returned, that can internally not be parsed to a long value.

### How do you reproduce the issue?
Try to fetch more than 100 orders from the API.

### Do you have a unit test that can demonstrate the bug?
No.

### Can you identify the location in the source code where the problem exists?
Yes. It's in ```ExtensionsForCoinbaseProClient.GetPagedJsonAsync``` method, where the Before/After headers are trying to be parsed to a long value.

### If the bug is confirmed, would you be willing to submit a PR?
Yes. In fact, I have already tried to fix that locally and succeeded by changing the Before and After properties from ```long``` to ```string```.

**Comment by bchavez** [comment] 2021-01-30 16:24
Thank you @devax for the report. Let me try to reproduce the issue; check your PR; then if all is okay, I will merge and make a new release.

Please make sure the PR can be edited by the maintainer (me) so I can touch-up the PR if necessary before merging.

Thanks.

**Comment by bchavez** [comment] 2021-01-30 17:13
Hi @devax ,

I created over 1000 orders on Sandbox. I cannot get the paged array to output any "Before" or "After" values with the following API call:
* `await this.client.Orders.GetAllOrdersAsync();`

```
{
  "Data": [
     1000+ orders
  ],
  "Before": null,
  "After": null,
  "Message": null
}
```
I'm not saying your wrong; I just need more information and additional proof of what is actually happening before making any modifications to the code.

I do see ***some*** evidence that before/after can be date & time strings, but these are in the HTTP headers, not in the JSON data itself:

![image](https://user-images.githubusercontent.com/478118/106363075-23a04d00-62db-11eb-8f1f-24c8150a29e6.png)

**Comment by devax** [comment] 2021-01-30 18:31
That's actually the bug I'm reporting.
Cb-Before and Cb-After headers contain a date time string in that case. The API as it is cannot handle these strings and will set Before and After fields to ```null```.

When you do the same with the code in my PR, Before and After fields will correctly reflect the same date time string the headers provide and subsequent calls with these before/after values will succeed.

Please let me know if there is anything else I can provide to help.

**Comment by bchavez** [comment] 2021-01-30 18:48
Hi @devax,

Ah, okay, thank you so much for the clarification. It's been a while since I looked at this code.

Now I see, the `GetPagedJsonAsync<T>()` extension method hoists the header values into the response object the code gives you. And ***that's*** the reason why it's `null`.

https://github.com/bchavez/Coinbase.Pro/blob/ccce9d137d4b2b0d9cc231836d4814577273c7d5/Source/Coinbase.Pro/ExtensionsForCoinbaseProClient.cs#L30-L40

Alrighty, back on track. Thank you.

**Comment by devax** [comment] 2021-01-30 18:58
Hey @bchavez , thank you so much for your quick response and for your close look at that issue!
That's exactly what the PR tries to address. But feel free to fix this in your own PR if you prefer. I would just like to see it fixed.
Again, thank you for a great repository that helped me transform my old python code to a more stable C# implementation. :-)

**Comment by bchavez** [comment] 2021-01-30 19:01
No problem @devax ; I'm reviewing your PR now. I might make a few edits; nothing serious, mostly reverting changes that aren't directly related to the issue at hand. Mostly to keep yourPR narrowly focused on resolving the issue only.

Also, double-checking to make sure we didn't miss any other API calls with `long` before & after.

**Comment by devax** [comment] 2021-01-30 19:07
Awesome! Thank you very much for taking care of this issue!

**Closed** 2021-01-30 19:46 UTC

**Comment by bchavez** [comment] 2021-01-30 20:01
New **Coinbase.Pro** `v4.0.1` version released.

https://www.nuget.org/packages/Coinbase.Pro/4.0.1

Thanks @devax for your help and PR!
